### ISSUE TITLE
DFS Implementation

### ISSUE THREAD

**Issue by zrygan** [zrygan/DSA-Project#6]
See DFS Implementation in the project specifications, [here](https://drive.google.com/file/d/1-C6DqAbFEAy9IENuFs8IMzot3bH-jLls/view?usp=drive_link).

@jazjimenez @Viennbalcita

**Comment by jazjimenez** [comment]
@jazjimenez will be doing the DFS Implementation

**Comment by jazjimenez** [comment]
done, for debugging
